### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#70]
As a student, I will want to have a nicely designed homepage so that I will easily be able to find what I'm looking for.

- Better layout/placement of buttons.
- Only TBD is logo design

Resources:
- https://m3.material.io/
- https://developer.android.com/jetpack/compose/designsystems/material3

Task list:
- [x] [Remove "Name:" from category names](https://github.com/SeattleColleges/belindas-closet-android/issues/94)
- [x] [Create composable for NSC logo icon](https://github.com/SeattleColleges/belindas-closet-android/issues/94)
- [x] [Change colors according to NSC's theme colors](https://github.com/SeattleColleges/belindas-closet-android/issues/105)
- [x] [Create a clickable category w/ picture and name for each clothing type](https://github.com/SeattleColleges/belindas-closet-android/issues/120)

![Image](https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/0e045e7c-5556-48f5-9863-836795b79bca)

**Comment by brinkbrink** [comment]
For now, hold off on the icon/color change idea. Let's just do NSC mascot and colors.

**Comment by taylorpapke** [comment]
Let's make more categories like dress and shoes pictures below for all of the products @ https://github.com/SeattleColleges/belindas-closet-android/blob/main/app/src/main/java/com/example/belindas_closet/model/Product.kt

![Image](https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/6e20e6b7-6564-4185-8977-717c614a9dd0)
